version: "3.8"

services:
  djangoapp:
    build: .
    ports:
      - "8080:8080"
    expose:
      - 8080
    restart: always

    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@admin.com
      DJANGO_SUPERUSER_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stbootcamp

    command: bash -c "python manage.py initadmin; gunicorn -b 0.0.0.0:8080 --workers 3 snapptrip.wsgi"

  djangoapp2:
    build: .
    expose:
      - 8080
    restart: always
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@admin.com
      DJANGO_SUPERUSER_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stbootcamp

    command: bash -c "python manage.py makemigrations condition ruleaction condition; python manage.py migrate; python manage.py initadmin; gunicorn -b 0.0.0.0:8080 --workers 3 snapptrip.wsgi"

  db:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stbootcamp

  lb:
    image: nginx:1.21.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf