version: "3.8"

services:
  djangoapp:
    build: .
    expose:
      - 8080

  djangoapp2:
    build: .
    expose:
      - 8080

  db:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "stbootcamp"

  lb:
    image: nginx:1.21.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf