# Generated by Django 4.1 on 2022-08-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("action", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                ("rule_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[("D", "DISCOUNT"), ("M", "MARKUP")], max_length=1
                    ),
                ),
                ("sensitive_condition_list", models.CharField(max_length=1000)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="action.action"
                    ),
                ),
            ],
        ),
    ]
