# Generated by Django 4.0.6 on 2022-08-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('condiotion', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
            ],
        ),
    ]
